### ISSUE TITLE
[1.12.2] [1.2.1+] Magic Arsenal breaks light source texture from Astral Sorcerys Illumination wand.

### ISSUE THREAD

**Issue by wamc2017** [elytra/MagicArsenal#2]
Hi,

if Magic Arsenal in version 1.2.1 or higher and Astral Sorcery are installed together the light sources from the Illumination wand are broken:

![2018-06-05_13 47 09](https://user-images.githubusercontent.com/33242447/40974428-cac91654-68c7-11e8-9c71-e1ce84346023.png)

In versions 1.2.0 or below everything is ok:
![2018-06-05_13 50 55](https://user-images.githubusercontent.com/33242447/40974445-dafb0c62-68c7-11e8-81c0-5dc0d06a2b62.png)

Don't know if this issue is on your or on Astral Sorcerys side, but removing your mod or downgrading it fixes the problem.

Mods used to test this issue (no other mods installed):
astralsorcery-1.12.2-1.8.10
Baubles-1.12-1.5.2
jei_1.12.2-4.9.2.196
MagicArsenal-MC1.12_ver1.2.0 or MagicArsenal-MC1.12_ver1.2.4
forge-14.23.4.2707

Thanks for looking into it.

Best regards,
wamc

**Comment by falkreon** [comment]
This bug is fascinating! I'll have some time tomorrow to look into it, but I think it's the BlendFunc and not the lighting. Often for effects like these you use premultiplied alpha, and then set the color values "higher" than 1 would be at that alpha to make a fiery glow. The fix will probably just be an extra tryBlendFuncSeparate call, but I'll have to repro and confirm first.

**Comment by falkreon** [comment]
The problem repro'd just fine in dev. As these things sometimes go, it wasn't what I thought! So those smoke cards are gray textures. The color comes from the vertex colors. The blend func is just the normal alpha / 1-srcAlpha. I was trying to restore state by re-enabling lighting, but it turns out that's the one thing AS doesn't explicitly set before it renders. Fixed now :)
